createOrReplace

	table VictimisationByStationJuly2014To5May2025
		lineageTag: f2d9d0d1-e8ab-4f0a-b384-94939447fdfe

		column 'Anzsoc Division'
			dataType: string
			lineageTag: 60fce84f-72a7-4aa6-a566-997fa35e1e99
			summarizeBy: none
			sourceColumn: Anzsoc Division

			annotation SummarizationSetBy = Automatic

		column 'Year Month'
			dataType: string
			lineageTag: 02fc72cc-ee12-48b8-9d01-be0a5260d8e3
			summarizeBy: none
			sourceColumn: Year Month

			annotation SummarizationSetBy = Automatic

		column Victimisations
			dataType: int64
			formatString: 0
			lineageTag: 44a1d3c8-fe21-4e55-bb7e-d440dc475667
			summarizeBy: sum
			sourceColumn: Victimisations

			annotation SummarizationSetBy = Automatic

		column Location
			dataType: string
			lineageTag: 7a0d934f-274e-44b0-8aa9-a2d93ce199ed
			summarizeBy: none
			sourceColumn: Location

			annotation SummarizationSetBy = Automatic

		column 'Location Type'
			dataType: string
			lineageTag: 303a4887-ebbf-4e32-8563-3847a392b4d8
			summarizeBy: none
			sourceColumn: Location Type

			annotation SummarizationSetBy = Automatic

		column 'Territorial Authority'
			dataType: string
			lineageTag: 32f4ecf2-a7a8-4a4f-a6cc-0122b883b624
			summarizeBy: none
			sourceColumn: Territorial Authority

			annotation SummarizationSetBy = Automatic

		column 'Police Station'
			dataType: string
			lineageTag: 84b02f55-aeab-4b59-ac79-c8fa72f1149a
			summarizeBy: none
			sourceColumn: Police Station

			annotation SummarizationSetBy = Automatic

		column 'Police District'
			dataType: string
			lineageTag: 818e0f3a-2a02-4403-abdc-60592290d048
			summarizeBy: none
			sourceColumn: Police District

			annotation SummarizationSetBy = Automatic

		column 'Police Area'
			dataType: string
			lineageTag: d4b196e8-746e-4ae3-be90-91cce071f51e
			summarizeBy: none
			sourceColumn: Police Area

			annotation SummarizationSetBy = Automatic

		column Person/Organisation
			dataType: string
			lineageTag: 3bf833f1-14ee-44d4-980b-f94c8445dbe5
			summarizeBy: none
			sourceColumn: Person/Organisation

			annotation SummarizationSetBy = Automatic

		column Weapon
			dataType: string
			lineageTag: d9da4aa8-2a87-4412-9193-0b111da0ca38
			summarizeBy: none
			sourceColumn: Weapon

			annotation SummarizationSetBy = Automatic

		column 'Weapons Used'
			dataType: string
			lineageTag: 9663da44-209f-4aae-b369-46233a38b9f6
			summarizeBy: none
			sourceColumn: Weapons Used

			annotation SummarizationSetBy = Automatic

		column 'Age Group'
			dataType: string
			lineageTag: 9113f1cd-72eb-4cfb-84d0-a21b35000df8
			summarizeBy: none
			sourceColumn: Age Group

			annotation SummarizationSetBy = Automatic

		column 'Anzsoc Group'
			dataType: string
			lineageTag: 3da60e26-11a0-4b97-b70d-18e9259ea766
			summarizeBy: none
			sourceColumn: Anzsoc Group

			annotation SummarizationSetBy = Automatic

		column 'Anzsoc Subdivision'
			dataType: string
			lineageTag: 0857ba28-6a08-4866-828a-7664d0da5bb8
			summarizeBy: none
			sourceColumn: Anzsoc Subdivision

			annotation SummarizationSetBy = Automatic

		column 'Anzsoc Subgroup'
			dataType: string
			lineageTag: 48f92323-b5b8-4abe-b474-d1521ba7c00d
			summarizeBy: none
			sourceColumn: Anzsoc Subgroup

			annotation SummarizationSetBy = Automatic

		column YearMonth
			dataType: dateTime
			formatString: Long Date
			lineageTag: e4cd37bb-7dd5-49ce-8f87-d497fa21b2da
			summarizeBy: none
			sourceColumn: YearMonth

			variation Variation
				isDefault
				relationship: 0cc15a7c-025e-4c69-87f3-ebb57ad55fe4
				defaultHierarchy: LocalDateTable_b3f00e49-df90-4d4a-b75d-3a6acf1e3a17.'Date Hierarchy'

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		column 'InterpolatedPopulation.interpolated_pop'
			dataType: double
			lineageTag: 728c62ac-e88c-42a4-82ef-cef66c336350
			summarizeBy: sum
			sourceColumn: InterpolatedPopulation.interpolated_pop

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		partition VictimisationByStationJuly2014To5May2025 = m
			mode: import
			source =
					let
					    Source = Csv.Document(File.Contents("C:\Users\BhodanSzymanilk\OneDrive - RetailMag\Documents\wd\VictimisationsByPoliceStation\VictimisationByStationJuly2014To5May2025_og.csv"),[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Anzsoc Division", type text}, {"Year Month", type text}, {"Victimisations", Int64.Type}, {"Location", type text}, {"Location Type", type text}, {"Territorial Authority", type text}, {"Police Station", type text}, {"Police District", type text}, {"Police Area", type text}, {"Person/Organisation", type text}, {"Weapon", type text}, {"Weapons Used", type text}, {"Age Group", type text}, {"Anzsoc Group", type text}, {"Anzsoc Subdivision", type text}, {"Anzsoc Subgroup", type text}}),
					    #"Added Custom" = Table.AddColumn(#"Changed Type", "YearMonth", each Date.FromText([Year Month], [Format="M/d/yyyy", Culture="us-EN"]), Date.Type),
					    #"Merged Queries" = Table.NestedJoin(#"Added Custom", {"YearMonth"}, InterpolatedPopulation, {"year_month"}, "InterpolatedPopulation", JoinKind.LeftOuter),
					    #"Expanded InterpolatedPopulation" = Table.ExpandTableColumn(#"Merged Queries", "InterpolatedPopulation", {"interpolated_pop"}, {"InterpolatedPopulation.interpolated_pop"})
					in
					    #"Expanded InterpolatedPopulation"

		annotation PBI_ResultType = Table

		annotation PBI_NavigationStepName = Navigation

