createOrReplace

	table VictimisationsByYearMB2021To2025
		lineageTag: 9a56a415-1a37-40d0-9cda-c6762e205fea

		column MBRaw
			dataType: int64
			formatString: 0
			lineageTag: 1c18b1b5-fe29-43c9-92e5-a4f8d29a818d
			summarizeBy: sum
			sourceColumn: MBRaw

			annotation SummarizationSetBy = Automatic

		column Year
			dataType: string
			lineageTag: 051121d7-4745-4b5c-ae2c-c9b164a7307d
			summarizeBy: none
			sourceColumn: Year

			annotation SummarizationSetBy = Automatic

		column SumVictimisations
			dataType: double
			lineageTag: 3f9f0570-8a00-4553-bce7-3703c4e995f5
			summarizeBy: sum
			sourceColumn: SumVictimisations

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Location Type'
			dataType: string
			lineageTag: cc1a910a-b3cd-48d6-9611-b990d27a6036
			summarizeBy: none
			sourceColumn: Location Type

			annotation SummarizationSetBy = Automatic

		column Meshblock
			dataType: string
			lineageTag: f01534cb-14ea-4bc8-8015-5416d27dbb4d
			summarizeBy: none
			sourceColumn: Meshblock

			annotation SummarizationSetBy = Automatic

		column 'CCTVCamerasByMeshblock2013.CleanMeshblock'
			dataType: string
			lineageTag: edc33e34-8395-4aa4-878c-b9574ba21b98
			summarizeBy: none
			sourceColumn: CCTVCamerasByMeshblock2013.CleanMeshblock

			annotation SummarizationSetBy = Automatic

		column 'CCTVCamerasByMeshblock2013.[Count of Points]'
			dataType: int64
			formatString: 0
			lineageTag: 367ab94c-4bcf-45a3-b893-c6b1a0db5619
			summarizeBy: sum
			sourceColumn: CCTVCamerasByMeshblock2013.[Count of Points]

			annotation SummarizationSetBy = Automatic

		column 'CCTVCamerasByMeshblock2013.AreaUnitName'
			dataType: string
			lineageTag: d7aeadcb-5a23-4fe5-ad28-67bcb823f7c0
			summarizeBy: none
			sourceColumn: CCTVCamerasByMeshblock2013.AreaUnitName

			annotation SummarizationSetBy = Automatic

		column 'CCTVCamerasByMeshblock2013.TLAName'
			dataType: string
			lineageTag: 0366ac76-45c8-4e9d-b373-893935ed75be
			summarizeBy: none
			sourceColumn: CCTVCamerasByMeshblock2013.TLAName

			annotation SummarizationSetBy = Automatic

		column 'Territorial Authority'
			dataType: string
			lineageTag: f99dc82e-cee2-49f2-a60a-67774d659d24
			summarizeBy: none
			sourceColumn: Territorial Authority

			annotation SummarizationSetBy = Automatic

		column 'ANZSOC Division'
			dataType: string
			lineageTag: f0c9a113-1bdd-4cd2-82cc-1853af903cc9
			summarizeBy: none
			sourceColumn: ANZSOC Division

			annotation SummarizationSetBy = Automatic

		partition VictimisationsByYearMB2021To2025 = m
			mode: import
			source = ```
					let
					    Source = Csv.Document(File.Contents("C:\Users\someone\OneDrive - someorg\Documents\wd\VictimisationsByTimePlace\VictimisationsByTimePlace2021to2025.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
					    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					    #"Filtered Rows" = Table.SelectRows(#"Promoted Headers", each true),
					    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Location Type", type text}, {"ANZSOC Division", type text}, {"Victimisations", Int64.Type}, {"ANZSOC Group", type text}, {"Meshblock", Int64.Type}, {"Year Month", type date}}),
					    #"Clean Territorial Authority" = Table.TransformColumns(#"Changed Type", {{"Territorial Authority", each Text.Remove(_, {"."})}}),
					    #"Added Custom" = Table.AddColumn(#"Clean Territorial Authority", "Year", each Date.Year([#"Year Month"])),
					    #"Grouped Rows" = Table.Group(#"Added Custom", {"Year", "Meshblock", "Location Type", "Territorial Authority", "ANZSOC Division"}, {{"SumVictimisations", each List.Sum([Victimisations]), type nullable number}}),
					    #"Renamed Columns" = Table.RenameColumns(#"Grouped Rows",{{"Meshblock", "MBRaw"}}),
					    #"FilteredInvalidMeshblocks" = Table.SelectRows(#"Renamed Columns", each [MBRaw] > 0),
					    #"Added Custom1" = Table.AddColumn(#"FilteredInvalidMeshblocks", "Meshblock", each Text.PadStart(Text.From([MBRaw]), 7, "0")),
					    #"Merged Queries" = Table.NestedJoin(#"Added Custom1", {"Meshblock"}, CCTVCamerasByMeshblock2013, {"CleanMeshblock"}, "CCTVCamerasByMeshblock2013", JoinKind.LeftOuter),
					    #"Expanded CCTVCamerasByMeshblock2013" = Table.ExpandTableColumn(#"Merged Queries", "CCTVCamerasByMeshblock2013", 
					    {"CleanMeshblock", "Count of Points", "AreaUnitName", "TLAName"}, {"CCTVCamerasByMeshblock2013.CleanMeshblock", "CCTVCamerasByMeshblock2013.[Count of Points]", "CCTVCamerasByMeshblock2013.AreaUnitName","CCTVCamerasByMeshblock2013.TLAName"})
					in
					    #"Expanded CCTVCamerasByMeshblock2013"
					```

		annotation PBI_ResultType = Table

		annotation PBI_NavigationStepName = Navigation

